dimensionaltrees:
  commands:

    # Main command to DimensionalTrees [Admins]
    admin: "dtrees dimensionaltrees dt"

  blocks:
    end:

      # The block that will be the leaves in the End
      leaves: end_stone

      # The block that will be the logs in the End
      logs: purpur_block

    nether:

      # The block that will be the leaves in the Nether
      leaves: glowstone

      # The block that will be the logs in the Nether
      logs: gravel

  messages:

    # Warning for invalid blocks in config file
    invalid: "§cCan't grow the tree. A invalid material has been detected."

  options:

    # Send debug messages to the console.
    sendlog: true

    # Enable/disable the addon.
    enable_addon: true

    # Enable/disable the End trees.
    end_trees: true

    # Enable/disable the Nether Trees.
    nether_trees: true

    # List of the saplings/trees that will be transformed.
    # Add a # before to disable and remove the # to enable.
    # Like the default settings.
    tree_types:
      - oak
      - spruce
      - acacia
      - dark_oak
      - jungle
      - birch