name: BentoBox-DimensionalTrees
main: world.bentobox.dimensionaltrees.DimensionalTreesPladdon
version: ${project.version}${build.number}
api-version: "1.21"

authors: [AwakenedRedstone, tastybento, Poslovitch]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}
